baseURL = "https://chiffon-sequence.net"
languageCode = "jp-ja"
title = "シフォンシーケンス"
theme = "minimal"

[params]
    accent = "darkviolet"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/me"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/works/"
    name = "Works"
    weight = 3

[[menu.main]]
    url = "/shop/main"
    name = "Shop"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://twitter.com/Arvelt/"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://pixiv.me/arvelt"
    name = "link"
    weight = 2
